# -*- coding: utf-8 -*-
{
    'name': 'Finance Insights | 57 Advanced Reports & Dashboards Odoo Forgot',
    'version': '18.0.6.0.0',
    'category': 'Accounting/Accounting',
    'summary': '57 advanced finance screens for Odoo 19. Bilingual AR/EN. Community + Enterprise. Free LGPL-3.',
    'description': "Finance Insights — 57 screens.",
    'author': 'Moaz Nabil',
    'website': 'https://github.com/moaaznaabilali',
    'support': 'moaaznaabilali@gmail.com',
    'license': 'LGPL-3',
    'price': 0.00, 'currency': 'USD',
    'depends': ['base', 'web', 'mail', 'account'],
    'data': [
        'security/finance_insights_security.xml',
        'security/ir.model.access.csv',
        'views/dashboard_views.xml', 'views/cash_flow_views.xml', 'views/aged_receivable_views.xml',
        'views/ratios_views.xml', 'views/sales_analytics_views.xml', 'views/expense_analytics_views.xml',
        'views/cash_position_views.xml', 'views/customer_profitability_views.xml', 'views/burn_rate_views.xml',
        'views/customer_risk_views.xml', 'views/budget_heatmap_views.xml', 'views/working_capital_views.xml',
        'views/product_profitability_views.xml', 'views/three_statement_views.xml',
        'views/cfo_command_views.xml', 'views/aging_combined_views.xml', 'views/tax_dashboard_views.xml',
        'views/vendor_spend_views.xml', 'views/bank_reconciliation_views.xml', 'views/journal_audit_views.xml',
        'views/customer_concentration_views.xml', 'views/vendor_concentration_views.xml',
        'views/currency_exposure_views.xml', 'views/daily_sales_views.xml', 'views/late_invoices_views.xml',
        'views/liquidity_stress_views.xml', 'views/margin_salesperson_views.xml',
        'views/customer_ltv_views.xml', 'views/invoice_cycle_time_views.xml',
        'views/receivables_forecast_views.xml', 'views/vendor_payment_schedule_views.xml',
        'views/refund_rate_views.xml', 'views/days_to_pay_views.xml',
        'views/income_expense_donut_views.xml', 'views/cash_efficiency_views.xml',
        'views/top_movements_views.xml', 'views/recurring_revenue_views.xml',
        'views/customer_cohort_views.xml', 'views/multi_year_views.xml',
        'views/negative_balance_views.xml', 'views/anomalous_transactions_views.xml',
        'views/credit_notes_audit_views.xml', 'views/account_velocity_views.xml',
        'views/payment_method_mix_views.xml', 'views/top_discounts_views.xml',
        'views/year_end_checklist_views.xml', 'views/free_cash_flow_views.xml',
        'views/analytic_pl_views.xml', 'views/pl_forecast_views.xml',
        'views/customer_churn_views.xml', 'views/cross_sell_views.xml',
        'views/vendor_reliability_views.xml', 'views/tax_reconciliation_views.xml',
        'views/acquisition_velocity_views.xml', 'views/aov_trend_views.xml',
        'views/pricing_power_views.xml', 'views/margin_stability_views.xml',
        'views/menus.xml',
        'report/aged_receivable_report.xml', 'report/statement_of_account_report.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'mn_finance_insights/static/src/lib/chart.umd.min.js',
            'mn_finance_insights/static/src/common/**/*',
            'mn_finance_insights/static/src/**/*.js',
            'mn_finance_insights/static/src/**/*.xml',
            'mn_finance_insights/static/src/**/*.scss',
        ],
    },
    'images': ['static/description/banner.png'],
    'installable': True, 'application': True, 'auto_install': False,
}
